openapi: 3.0.0
info:
  title: Tigris Custom IAM APIs
  version: 1.0.0
  description: Tigris Custom IAM apis
servers:
  - url: "https://fly.iam.storage.tigris.dev"
paths:
  /?Action=CreateAccessKeyWithBucketsRole:
    post:
      parameters:
        - in: query
          name: Action
          required: true
          schema:
            type: string
            enum:
              - CreateAccessKeyWithBucketsRole
      summary:
        Convenience method for generating access-keys with bucket level roles
        attached.
      operationId: CreateAccessKeyWithBucketsRole
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAccessKeyWithBucketsRoleRequest"
      responses:
        "200":
          description: Constructed access key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAccessKeyResponse"
components:
  schemas:
    CreateAccessKeyWithBucketsRoleRequest:
      type: object
      properties:
        name:
          type: string
        buckets_role:
          type: array
          items:
            $ref: "#/components/schemas/BucketsRole"
    BucketsRole:
      type: object
      properties:
        bucket:
          type: string
        role:
          type: string
    CreateAccessKeyResponse:
      type: object
      properties:
        CommonResponse:
          $ref: "#/components/schemas/CommonResponse"
        CreateAccessKeyResult:
          type: object
          properties:
            AccessKey:
              $ref: "#/components/schemas/AccessKey"
    AccessKey:
      type: object
      properties:
        AccessKeyId:
          type: string
          sensitive: true
        CreateDate:
          type: string
          format: date-time
        SecretAccessKey:
          type: string
          sensitive: true
        Status:
          type: string
          enum:
            - Active
            - Inactive
        UserName:
          type: string
    CommonResponse:
      type: object
