openapi: 3.0.0
info:
  title: Tigris Object Store Custom APIs
  version: 1.0.0
  description: Tigris Object Store Custom APIs.
servers:
  - url: "https://fly.storage.tigris.dev"
paths:
  /?func=presign:
    post:
      parameters:
        - in: query
          name: func
          required: true
          schema:
            type: string
            enum:
              - presign
      summary: Convenience method for generating pre-signed URLs.
      operationId: TigrisPreSignUrlGenerator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TigrisPreSignUrlGeneratorRequest"
      responses:
        "200":
          description: Constructed signed URL
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TigrisPreSignUrlGeneratorResponse"
  /?explain=authz:
    post:
      parameters:
        - in: query
          name: explain
          required: true
          schema:
            type: string
            enum:
              - authz
        - in: query
          name: IncludeReason
          required: false
          schema: {}
          allowEmptyValue: true
          description: When present, adds the reasoning for authz decision.
      summary: Explain the authorization
      operationId: ExplainAuthz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExplainAuthzRequest"
      responses:
        "200":
          description: Explanation of the authz decisions.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExplainAuthzResponse"
  /:
    get:
      parameters:
        - in: query
          name: IncludeVisibility
          schema:
            type: boolean
          required: false
          description: When set to true, adds the visibility detail to response.
        - in: query
          name: IncludeOwnerInfo
          schema:
            type: boolean
          required: false
          description: When set to true, adds the owner detail to response.
        - in: query
          name: IncludeRegionsInfo
          schema:
            type: boolean
          required: false
          description: When set to true, adds the regions detail to response.
        - in: query
          name: IncludeStats
          schema:
            type: boolean
          required: false
          description: When set to true, adds the stats for bucket to response.
      summary: List buckets with options
      operationId: ListBuckets
      responses:
        "200":
          description: Lists the bucket with options.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Owner:
                    type: object
                    properties:
                      ID:
                        type: string
                      DisplayName:
                        type: string
                    required:
                      - ID
                  Buckets:
                    type: object
                    properties:
                      Bucket:
                        type: array
                        items:
                          type: object
                          properties:
                            Name:
                              type: string
                            CreationDate:
                              type: string
                              format: date-time
                            Visibility:
                              type: object
                              properties:
                                IsPublic:
                                  type: boolean
                              required:
                                - IsPublic
                            OwnerInfo:
                              type: object
                              properties:
                                OwnerUserId:
                                  type: string
                                OwnerHumanUserId:
                                  type: string
                              required:
                                - OwnerUserId
                                - OwnerHumanUserId
                            Regions:
                              type: string
                  Stats:
                    type: object
                    properties:
                      ActiveBuckets:
                        type: integer
                      TotalStorageBytes:
                        type: integer
                      TotalObjects:
                        type: integer
  /status:
    get:
      summary: Check health status
      operationId: getStatus
      responses:
        "200":
          description: Status is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
components:
  schemas:
    ExplainAuthzRequest:
      type: object
      properties:
        queries:
          type: array
          items:
            $ref: "#/components/schemas/ExplainAuthzQuery"
    ExplainAuthzQuery:
      type: object
      properties:
        bucket:
          type: string
        object:
          type: string
        operation:
          type: string
      required:
        - bucket
        - object
        - operation
    ExplainAuthzResponse:
      type: object
      properties:
        answers:
          type: array
          items:
            $ref: "#/components/schemas/ExplainAuthzAnswer"
    ExplainAuthzAnswer:
      type: object
      properties:
        query:
          $ref: "#/components/schemas/ExplainAuthzQuery"
        errorCode:
          type: string
        reason:
          type: string
    TigrisPreSignUrlGeneratorRequest:
      type: object
      properties:
        bucket:
          type: string
        key:
          type: string
        key_id:
          type: string
        key_name:
          type: string
        expires_in:
          type: integer
          format: int32
          description: Expiry time in seconds
        type:
          type: string
          enum:
            - GET
            - PUT
      required:
        - bucket
        - key
        - key_id
        - expires_in
        - type
    TigrisPreSignUrlGeneratorResponse:
      type: object
      properties:
        bucket:
          type: string
        key:
          type: string
        type:
          type: string
          enum:
            - GET
            - PUT
        url:
          type: string
        key_id:
          type: string
          description: optionally if the new key was constructed
        key_secret:
          type: string
          description: optionally if the new key was constructed
      required:
        - bucket
        - key
        - type
        - url
